AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CoachFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: veloclicks-coach
      CodeUri: coach/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
