"""car and activity

Revision ID: 07b88f84cfd6
Revises: 37cb1fa4e69b
Create Date: 2025-02-22 10:05:47.044345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b88f84cfd6'
down_revision = '37cb1fa4e69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_high',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.alter_column('elev_high',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('distance',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
