"""add membership_type to user

Revision ID: 08be98f60c3e
Revises: 2a234e29dfef
Create Date: 2025-11-22 18:16:41.939750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08be98f60c3e'
down_revision = '2a234e29dfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE membershiptype AS ENUM ('FREE_TIER', 'PREMIUM_TIER')")

    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_high',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)

    with op.batch_alter_table('vc_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_type', sa.Enum('FREE_TIER', 'PREMIUM_TIER', name='membershiptype'), nullable=False, server_default='FREE_TIER'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_user', schema=None) as batch_op:
        batch_op.drop_column('membership_type')

    # Drop the enum type
    op.execute("DROP TYPE membershiptype")

    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.alter_column('elev_high',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('distance',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
