"""adding fields to hold activity analytics

Revision ID: 1f8679617316
Revises: c3d06ba29e42
Create Date: 2026-03-20 12:23:01.339017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8679617316'
down_revision = 'c3d06ba29e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assessment_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('classification_source', sa.String(length=16), nullable=True))
        batch_op.alter_column('distance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_high',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('tss',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.alter_column('tss',
               existing_type=sa.Float(precision=12, asdecimal=1),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elev_high',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('distance',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('classification_source')
        batch_op.drop_column('confirmed_type')
        batch_op.drop_column('assessment_data')
        batch_op.drop_column('identification_data')

    # ### end Alembic commands ###
