"""car and activity

Revision ID: 37cb1fa4e69b
Revises: c1349873eaa8
Create Date: 2025-02-22 10:03:45.647584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cb1fa4e69b'
down_revision = 'c1349873eaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vc_strava_activity',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('start_date_local', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('distance', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('elapsed_time', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('moving_time', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('average_speed', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('max_speed', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('average_watts', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('max_watts', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('weighted_average_watts', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('average_heartrate', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('max_heartrate', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('suffer_score', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('average_cadence', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('total_elevation_gain', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('elev_low', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.Column('elev_high', sa.Float(precision=12, asdecimal=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vc_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vc_user.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vc_strava_activity')
    # ### end Alembic commands ###
