"""Add power metrics/ curve to activity

Revision ID: 6b258012bd44
Revises: 964b8f8810cc
Create Date: 2025-12-03 07:59:17.091655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b258012bd44'
down_revision = '964b8f8810cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rpe', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('power_curve_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_in_zones', sa.Text(), nullable=True))
        batch_op.alter_column('distance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('elev_high',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=12, asdecimal=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vc_strava_activity', schema=None) as batch_op:
        batch_op.alter_column('elev_high',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elev_low',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_elevation_gain',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_cadence',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('suffer_score',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_heartrate',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('weighted_average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_watts',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('max_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('average_speed',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('moving_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('elapsed_time',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('distance',
               existing_type=sa.Float(precision=12, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('time_in_zones')
        batch_op.drop_column('power_curve_data')
        batch_op.drop_column('rpe')
        batch_op.drop_column('ftp')

    # ### end Alembic commands ###
